version: '3'
services:

  tests:
    build: .
    image: aiopyrq:latest
    command: python -m pytest -vv tests
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  tests7:
    build: .
    image: aiopyrq:latest
    command: python -m pytest -vv tests
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis7

  tests6:
    build: .
    image: aiopyrq:latest
    command: python -m pytest -vv tests
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis6

  tests5:
    build: .
    image: aiopyrq:latest
    command: python -m pytest -vv tests
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis5

  redis:
    container_name: redis
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis7:
    container_name: redis
    image: redis:7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis6:
    container_name: redis
    image: redis:6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis5:
    container_name: redis
    image: redis:5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
